### ISSUE TITLE
Titos 2:3 typo

### ISSUE THREAD

**Issue by tmakarios** [Freely-Given-org/OpenEnglishTranslation--OET#3]
At the end of Titos 2:3, it currently says "They should [teaching](https://freely-given.org/OBD/ref/GrkWrd/TITc2v3w14.htm#Top) what is [good](https://freely-given.org/OBD/ref/GrkWrd/TITc2v3w14.htm#Top)".  It would be more grammatical to say either "They should teach what is good" or "They should be teaching what is good".

**Comment by RobH123** [comment]
Thanks, fixed via 517690b (although website is only updated every week or two).
